<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><c:out value="${lesson.title}"/> — Lexora</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/lexora.css"></head><body>
<%@ include file="shared/header.jspf" %><main class="reading-page"><a class="back-link" href="${pageContext.request.contextPath}/">← Back to the open shelf</a>
<header class="reading-heading"><p class="eyebrow"><c:out value="${lesson.theme}"/> · <c:out value="${lesson.language}"/></p><h1><c:out value="${lesson.title}"/></h1><p class="reading-subtitle"><c:out value="${lesson.subtitle}"/></p><div class="lesson-meta centered"><span><c:out value="${lesson.proficiencyLevel}"/></span><span>·</span><span>${lesson.readingMinutes} MIN READ</span></div></header>
<div class="reading-layout"><article class="story-paper"><div class="paper-topline"><span>FROM THE LEXORA COMMONPLACE BOOK</span><span>✳</span></div><div class="story-text"><c:out value="${lesson.content}"/></div><div class="paper-end">✳ &nbsp; FIN DE L'HISTOIRE &nbsp; ✳</div></article>
<aside class="word-sidebar"><p class="eyebrow">WORDS TO KEEP</p><h2>A pocket glossary.</h2><p class="sidebar-intro">A few words from this story to carry into your day.</p>
<c:forEach var="word" items="${vocabulary}"><article class="word-card"><span class="word-pronunciation"><c:out value="${word.pronunciation}"/></span><h3><c:out value="${word.word}"/></h3><p><c:out value="${word.translation}"/></p><small><c:out value="${word.example}"/></small></article></c:forEach>
<div class="culture-note"><span>✳ A CULTURAL MARGIN NOTE</span><p><c:out value="${lesson.culturalNote}"/></p></div><div class="coming-soon"><span>THE NEXT PAGE</span><strong>Comprehension questions</strong><p>Quiz submission and saved vocabulary are planned for the next milestone.</p></div></aside></div></main>
<footer class="site-footer"><a class="brand" href="${pageContext.request.contextPath}/"><span class="brand-mark">✳</span><span>lexora</span></a><span>Keep a word. Keep a world.</span><span>LEXORA / READING ROOM</span></footer></body></html>
